name: Issue Notifier

on:
  issues:
    types: [opened]

jobs:
  notify:
    name: "Telegram notification"
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message about new issue
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸš€ New issue created by ${{ github.actor }} in ${{ github.repository }}!

            ğŸ“Œ Title: ${{ github.event.issue.title }}

            ğŸ”— Link: ${{ github.event.issue.html_url }}

            ğŸ“ Description:
            ${{ github.event.issue.body }}
